server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead_authuser
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
      jdbc:
        lob.non-contextual-creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
    deserialization:
      fail-on-unknown-properties: false
viacep: 'viacep.com.br/ws'

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO

ead:
  api:
    url:
      course: http://localhost:8082/api/course
