server:
  port: 8081
  servlet:
    context-path: '/ead-authuser/'
spring:
  application:
    name: ead-authuser-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ead_authuser_v2
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: 'update'
      jdbc:
        lob.non-contextual-creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
    deserialization:
      fail-on-unknown-properties: false
  rabbitmq:
    addresses: amqps://pkarejhb:3wvfp-xlq2wCbIu6ZzR_lFhs64FhQ9Ew@whale.rmq.cloudamqp.com/pkarejhb

viacep: 'viacep.com.br/ws'

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    org.springframework.cloud.loadbalancer: TRACE
ead:
  api:
    url:
      course: http://ead-api-gateway/ead-course
  broker:
    exchange:
      userEvent: ead.userevent
#EUREKA CONFIGURATIONS AUTHUSER CLIENT
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

