server:
  port: 8082
spring:
  datasource:
    url: jdbc:h2:mem:ead_course
    username: sa
    password:
  jpa:
    hibernate:
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true