health:
  config:
    enabled: false
server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gabrielffguimaraes/ead-config-server
          default-label: main
          username: gabrielffguimaraes
          password: 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

ead:
  configServer:
    username: configserver
    password: ead123cs
  serviceRegistry:
    username: serviceregistry
    password: ead123r

eureka:
  client:
    serviceUrl:
      defaultZone:  'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost
