server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gabrielffguimaraes/ead-config-server
          default-label: main
          username: gabrielffguimaraes
          password: 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

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost
