server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gabrielffguimaraes/ead-config-server
          default-label: main
          username: gabrielffguimaraes
          password: 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

ead:
  configServer:
    username: configserver
    password: ead123cs
  serviceRegistry:
    username: serviceregistry
    password: ead123r

eureka:
  client:
    serviceUrl:
      defaultZone:  'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost
