server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gabrielffguimaraes/ead-config-server
          default-label: main
          username: gabrielffguimaraes
          password: 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

ead:
  configServer:
    username: configserver
    password: ead123cs
  serviceRegistry:
    username: serviceregistry
    password: ead123r

eureka:
  client:
    serviceUrl:
      defaultZone:  'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost
